# MCSD6215 Master Project
Name: Tan Boon Chu 

Matrics No.: MCS211006

Project Title: EDA and Recommender System for Steam Online Gaming Platform

## Data Import

In [133]:
import pandas as pd
import numpy as np

In [134]:
# Import PyDrive and associated libraries
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client
# This only needs to be done once per notebook
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

Import first dataset

In [135]:
# Download a file based on its file ID.

file_id = '1OUlfevxyjoVxF3qSgzN1o7IBcGHN5S76'
downloaded = drive.CreateFile({'id': file_id})

# Save file in Colab memory
downloaded.GetContentFile('steamspy_data.csv')  

# Read Data file
df1 = pd.read_csv('steamspy_data.csv')

Import second dataset with descriptions

In [136]:
file_id = '1pVwlu6jdg2N2ke0jju9xng3V1SD_u8Ln' 
downloaded = drive.CreateFile({'id': file_id})

downloaded.GetContentFile('steam_app_data.csv')  
# Read Data file
df2 = pd.read_csv('steam_app_data.csv')

In [137]:
# Extract only the description from 2nd dataset
df2 = df2[['name','detailed_description']]

## Data Integration

In [138]:
# Data Integration
df = pd.merge(df1, df2, on='name', how='outer')
df = pd.DataFrame(df)

In [139]:
# print out number of rows and columns
print('Rows:', df.shape[0])
print('Columns:', df.shape[1])

# View first 5 rows
df.head()

Rows: 30083
Columns: 21

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,...,median_forever,median_2weeks,price,initialprice,discount,languages,genre,ccu,tags,detailed_description
0,10.0,Counter-Strike,Valve,Valve,NaN,124534.0,3339.0,0.0,"10,000,000 .. 20,000,000",17612.0,...,317.0,26.0,999.0,999.0,0.0,"English, French, German, Italian, Spanish - Sp...",Action,14923.0,"{'Action': 2681, 'FPS': 2048, 'Multiplayer': 1...",Play the world's number 1 online action game. ...
1,20.0,Team Fortress Classic,Valve,Valve,NaN,3318.0,633.0,0.0,"5,000,000 .. 10,000,000",277.0,...,62.0,15.0,499.0,499.0,0.0,"English, French, German, Italian, Spanish - Sp...",Action,87.0,"{'Action': 208, 'FPS': 188, 'Multiplayer': 172...",One of the most popular online action games of...
2,30.0,Day of Defeat,Valve,Valve,NaN,3416.0,398.0,0.0,"5,000,000 .. 10,000,000",187.0,...,34.0,0.0,499.0,499.0,0.0,"English, French, German, Italian, Spanish - Spain",Action,130.0,"{'FPS': 138, 'World War II': 122, 'Multiplayer...",Enlist in an intense brand of Axis vs. Allied ...
3,40.0,Deathmatch Classic,Valve,Valve,NaN,1273.0,267.0,0.0,"5,000,000 .. 10,000,000",258.0,...,184.0,0.0,499.0,499.0,0.0,"English, French, German, Italian, Spanish - Sp...",Action,4.0,"{'Action': 85, 'FPS': 71, 'Multiplayer': 58, '...",Enjoy fast-paced multiplayer gaming with Death...
4,50.0,Half-Life: Opposing Force,Gearbox Software,Valve,NaN,5250.0,288.0,0.0,"5,000,000 .. 10,000,000",624.0,...,415.0,0.0,499.0,499.0,0.0,"English, French, German, Korean",Action,71.0,"{'FPS': 235, 'Action': 211, 'Sci-fi': 166, 'Si...",Return to the Black Mesa Research Facility as ...

## Data Cleaning

In [140]:
df.isnull().sum()

appid                     622
name                        5
developer                 824
publisher                 909
score_rank              30025
positive                  622
negative                  622
userscore                 622
owners                    622
average_forever           622
average_2weeks            622
median_forever            622
median_2weeks             622
price                     653
initialprice              646
discount                  646
languages                 718
genre                     776
ccu                       622
tags                      622
detailed_description      882
dtype: int64

In [141]:
df.drop(['score_rank', 'userscore', 'publisher', 'initialprice', 'discount', 
         'average_2weeks', 'median_2weeks', 'ccu', 'tags'], axis=1, inplace=True)
df.head()

,appid,name,developer,positive,negative,owners,average_forever,median_forever,price,languages,genre,detailed_description
0,10.0,Counter-Strike,Valve,124534.0,3339.0,"10,000,000 .. 20,000,000",17612.0,317.0,999.0,"English, French, German, Italian, Spanish - Sp...",Action,Play the world's number 1 online action game. ...
1,20.0,Team Fortress Classic,Valve,3318.0,633.0,"5,000,000 .. 10,000,000",277.0,62.0,499.0,"English, French, German, Italian, Spanish - Sp...",Action,One of the most popular online action games of...
2,30.0,Day of Defeat,Valve,3416.0,398.0,"5,000,000 .. 10,000,000",187.0,34.0,499.0,"English, French, German, Italian, Spanish - Spain",Action,Enlist in an intense brand of Axis vs. Allied ...
3,40.0,Deathmatch Classic,Valve,1273.0,267.0,"5,000,000 .. 10,000,000",258.0,184.0,499.0,"English, French, German, Italian, Spanish - Sp...",Action,Enjoy fast-paced multiplayer gaming with Death...
4,50.0,Half-Life: Opposing Force,Gearbox Software,5250.0,288.0,"5,000,000 .. 10,000,000",624.0,415.0,499.0,"English, French, German, Korean",Action,Return to the Black Mesa Research Facility as ...

In [142]:
df['price'] = df['price'].fillna(df['price'].mean())
df['languages'] = df['languages'].fillna('English')
df[['developer','genre']] = df[['developer','genre']].fillna('Other')
df.isnull().sum()

appid                   622
name                      5
developer                 0
positive                622
negative                622
owners                  622
average_forever         622
median_forever          622
price                     0
languages                 0
genre                     0
detailed_description    882
dtype: int64

In [143]:
# Drop row on appid, name, and detailed description having null values
df.dropna(inplace = True)
df.isnull().sum()

appid                   0
name                    0
developer               0
positive                0
negative                0
owners                  0
average_forever         0
median_forever          0
price                   0
languages               0
genre                   0
detailed_description    0
dtype: int64

In [149]:
df.duplicated().sum()

20

In [150]:
df.duplicated(subset='name').sum()

199

In [151]:
df[df.duplicated(subset='name',keep=False)]

,appid,name,developer,positive,negative,owners,average_forever,median_forever,price,languages,genre,detailed_description
114,1300.0,SiN Episodes: Emergence,Ritual Entertainment,468.0,61.0,"100,000 .. 200,000",0.0,0.0,999.0,"English, Russian, French",Action,"You are John Blade, commander of HardCorps, an..."
115,1300.0,SiN Episodes: Emergence,Ritual Entertainment,468.0,61.0,"100,000 .. 200,000",0.0,0.0,999.0,"English, Russian, French",Action,"You are John Blade, commander of HardCorps, an..."
116,1300.0,SiN Episodes: Emergence,Ritual Entertainment,468.0,61.0,"100,000 .. 200,000",0.0,0.0,999.0,"English, Russian, French",Action,"You are John Blade, commander of HardCorps, an..."
117,1309.0,SiN Episodes: Emergence,Ritual Entertainment,322.0,45.0,"200,000 .. 500,000",0.0,0.0,999.0,"English, Russian, French",Action,"You are John Blade, commander of HardCorps, an..."
118,1309.0,SiN Episodes: Emergence,Ritual Entertainment,322.0,45.0,"200,000 .. 500,000",0.0,0.0,999.0,"English, Russian, French",Action,"You are John Blade, commander of HardCorps, an..."
...,...,...,...,...,...,...,...,...,...,...,...,...
25991,998820.0,Cortex,Milan Toth,5.0,0.0,"0 .. 20,000",0.0,0.0,0.0,English,Action,&quot;You are a thought. A thought to be born....
26932,942050.0,2048,"Lucas Alexander Visual Arts, Nicolai Clemmense...",4.0,0.0,"0 .. 20,000",0.0,0.0,499.0,English,"Casual, Indie, Strategy",2048 is a classic puzzle with a simple goal; r...
26933,942050.0,2048,"Lucas Alexander Visual Arts, Nicolai Clemmense...",4.0,0.0,"0 .. 20,000",0.0,0.0,499.0,English,"Casual, Indie, Strategy","2048 is played on a 4×4 grid, with numbered ti..."
26934,1026330.0,2048,Dexion Games,0.0,1.0,"0 .. 20,000",0.0,0.0,99.0,English,"Casual, Indie, Simulation",2048 is a classic puzzle with a simple goal; r...
26935,1026330.0,2048,Dexion Games,0.0,1.0,"0 .. 20,000",0.0,0.0,99.0,English,"Casual, Indie, Simulation","2048 is played on a 4×4 grid, with numbered ti..."

In [152]:
df.drop_duplicates(subset='name', keep="first", inplace=True)

In [153]:
df.duplicated(subset='name').sum()

0

In [154]:
# Data type
df.dtypes

appid                   float64
name                     object
developer                object
positive                float64
negative                float64
owners                   object
average_forever         float64
median_forever          float64
price                   float64
languages                object
genre                    object
detailed_description     object
dtype: object

In [155]:
df = df.astype({'appid':int, 'positive':int,'negative':int})

## Feature Engineering

In [156]:
df['Ratings'] = df.positive - df.negative
df['Is_Free'] = np.where(df['price']==0, 'Free', 'Paid')
df['English'] = np.where(df['languages'].str.contains("English"), 'Yes', 'No')

In [157]:
df['download'] = df['owners'].str.replace(',', '').str.split(' .. ')
df['download'] = df['download'].apply(lambda x: int(x[1]))

In [158]:
df = df.rename({
    'average_forever': 'average_playtime',
    'median_forever': 'median_playtime'
}, axis=1)

In [159]:
df.loc[df['price'] > 0, 'price'] /= 100
df['appid'] = df.appid // 10

In [160]:
print('Rows:',df.shape[0])
print('Columns:',df.shape[1])
df.head()

Rows: 28375
Columns: 16

,appid,name,developer,positive,negative,owners,average_playtime,median_playtime,price,languages,genre,detailed_description,Ratings,Is_Free,English,download
0,1,Counter-Strike,Valve,124534,3339,"10,000,000 .. 20,000,000",17612.0,317.0,9.99,"English, French, German, Italian, Spanish - Sp...",Action,Play the world's number 1 online action game. ...,121195,Paid,Yes,20000000
1,2,Team Fortress Classic,Valve,3318,633,"5,000,000 .. 10,000,000",277.0,62.0,4.99,"English, French, German, Italian, Spanish - Sp...",Action,One of the most popular online action games of...,2685,Paid,Yes,10000000
2,3,Day of Defeat,Valve,3416,398,"5,000,000 .. 10,000,000",187.0,34.0,4.99,"English, French, German, Italian, Spanish - Spain",Action,Enlist in an intense brand of Axis vs. Allied ...,3018,Paid,Yes,10000000
3,4,Deathmatch Classic,Valve,1273,267,"5,000,000 .. 10,000,000",258.0,184.0,4.99,"English, French, German, Italian, Spanish - Sp...",Action,Enjoy fast-paced multiplayer gaming with Death...,1006,Paid,Yes,10000000
4,5,Half-Life: Opposing Force,Gearbox Software,5250,288,"5,000,000 .. 10,000,000",624.0,415.0,4.99,"English, French, German, Korean",Action,Return to the Black Mesa Research Facility as ...,4962,Paid,Yes,10000000

## Data Export

In [161]:
from google.colab import files

df.to_csv('steam_clean_data.csv',index=False)
files.download('steam_clean_data.csv')